http:
  port: 8080
kafka:
  bootstrap-servers: localhost:9092
  group-id: incident-priority
  topic-incident-assignment-event: topic-incident-event
  topic-priority-zone-application-event: topic-priority-zone-event
incident-service: 